spring.application.name=auth-backend

server.port=8081

# PostgreSQL - misma base de datos actual de Vita+
spring.datasource.url=jdbc:postgresql://aws-0-us-east-1.pooler.supabase.com:6543/postgres?sslmode=require
spring.datasource.username=postgres.lrcpnehwvywypgppxhjr
spring.datasource.password=RedVitaMas+
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT
jwt.secret=cambia_esto_por_una_clave_larga_y_secreta_1234567890abcdef
jwt.expiration=86400000

# messaging-backend (verificacion de OTP)
messaging.service.url=http://localhost:8082

server.error.include-message=always

spring.datasource.hikari.maximum-pool-size=3
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.data-source-properties.prepareThreshold=0

# Hunter - validación de correos
hunter.api-key=82fa0ae2842bd288eaa820c27dbf9c8c3c3fc879